% Setup uicontrols at the left side of the window
% Position: 
% [left bottom width height]
txt = uicontrol('Parent',data.f,...
        'Style','text',...
        'Position',[5 S(4) - 200 100 40],...
        'String','NavMode');

data.popup = uicontrol('Parent',data.f,...
           'Style','popup',...
           'Position',[5 S(4)-200 100 25],...
           'String',{'Walk';'Examine';'Fly'},...
           'Callback',{@callback_test,data});
       
       
       
       