% Popul Control : VR Navigation Mode


txt = uicontrol('Parent',f,...
        'Style','text',...
        'Position',[5 710 100 40],...
        'String','NavMode');

data.popup = uicontrol('Parent',f,...
           'Style','popup',...
           'Position',[5 700 100 25],...
           'String',{'Walk';'Examine';'Fly'},...
           'Callback',{@callback_test,data});
